### ISSUE TITLE
CBaseAnimating::TestHitboxes is failing while doing trace

### ISSUE THREAD

**Issue by Noiwex** [Facepunch/garrysmod-issues#2320]
I don't have access to code, so I can give only what I have.
Basically what's happening: player looks at something, server tries to get his eyetrace and fails. I haven't discovered what causes crashes yet, like what entity or model.

Point of stop in TestHitboxes:
```
Dump of assembler code for function _ZN14CBaseAnimating12TestHitboxesERK5Ray_tjR10CGameTrace:
   0xed142990 <+0>:     push   %ebp
   0xed142991 <+1>:     mov    %esp,%ebp
   0xed142993 <+3>:     sub    $0x458,%esp
   0xed142999 <+9>:     mov    %ebx,-0xc(%ebp)
   0xed14299c <+12>:    mov    %esi,-0x8(%ebp)
   0xed14299f <+15>:    mov    %edi,-0x4(%ebp)
   0xed1429a2 <+18>:    mov    0x8(%ebp),%ebx
   0xed1429a5 <+21>:    mov    %ebx,(%esp)
   0xed1429a8 <+24>:    call   0xed09a710 <_ZN14CBaseAnimating11GetModelPtrEv>
   0xed1429ad <+29>:    mov    %eax,%esi
   0xed1429af <+31>:    test   %eax,%eax
   0xed1429b1 <+33>:    je     0xed1429d2 <_ZN14CBaseAnimating12TestHitboxesERK5Ray_tjR10CGameTrace+66>
   0xed1429b3 <+35>:    mov    (%eax),%eax
   0xed1429b5 <+37>:    mov    0x13a0(%ebx),%edx
   0xed1429bb <+43>:    lea    (%edx,%edx,2),%edi
   0xed1429be <+46>:    shl    $0x2,%edi
   0xed1429c1 <+49>:    add    0xb0(%eax),%edi
   0xed1429c7 <+55>:    add    %eax,%edi
   0xed1429c9 <+57>:    je     0xed1429d2 <_ZN14CBaseAnimating12TestHitboxesERK5Ray_tjR10CGameTrace+66>
=> 0xed1429cb <+59>:    mov    0x4(%edi),%eax
...
```

Backtrace:
```
(gdb) bt
#0  0xed1429cb in CBaseAnimating::TestHitboxes(Ray_t const&, unsigned int, CGameTrace&) ()
   from /home/nxserv/gserv/servers/drp2/garrysmod/bin/server_srv.so
#1  0xf606c3c7 in CEngineTrace::ClipRayToHitboxes(Ray_t const&, unsigned int, ICollideable*, CGameTrace*) ()
   from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#2  0xf606d0c8 in CEngineTrace::ClipRayToCollideable(Ray_t const&, unsigned int, ICollideable*, CGameTrace*) ()
   from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#3  0xf606deef in CEngineTrace::TraceRay(Ray_t const&, unsigned int, ITraceFilter*, CGameTrace*) ()
   from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#4  0xecfa62f8 in real__util__TraceLine(ILuaInterface*) ()
   from /home/nxserv/gserv/servers/drp2/garrysmod/bin/server_srv.so
#5  0xe74ab76b in lj_BC_FUNCC () from /home/nxserv/gserv/servers/drp2/garrysmod/bin/lua_shared_srv.so
#6  0xe749cadd in lua_pcall () from /home/nxserv/gserv/servers/drp2/garrysmod/bin/lua_shared_srv.so
#7  0xee20c1c0 in ?? ()
#8  0xe747f80a in CLuaInterface::CallFunctionProtected(int, int, bool) ()
   from /home/nxserv/gserv/servers/drp2/garrysmod/bin/lua_shared_srv.so
#9  0xecf9e995 in GarrysMod::Lua::Libraries::Timer::CallTimerFunction(int, std::string const&, std::string const&)
    () from /home/nxserv/gserv/servers/drp2/garrysmod/bin/server_srv.so
#10 0xecfa0581 in GarrysMod::Lua::Libraries::Timer::DoAdvancedTimers() ()
   from /home/nxserv/gserv/servers/drp2/garrysmod/bin/server_srv.so
#11 0xecfa07d5 in GarrysMod::Lua::Libraries::Timer::Cycle() ()
   from /home/nxserv/gserv/servers/drp2/garrysmod/bin/server_srv.so
#12 0xecf77880 in CGarrysMod::Think() () from /home/nxserv/gserv/servers/drp2/garrysmod/bin/server_srv.so
#13 0xece98a93 in CLuaGameSystem::FrameUpdatePreEntityThink() ()
   from /home/nxserv/gserv/servers/drp2/garrysmod/bin/server_srv.so
#14 0xecf11c80 in InvokePerFrameMethod(void (IGameSystemPerFrame::*)(), char const*) ()
   from /home/nxserv/gserv/servers/drp2/garrysmod/bin/server_srv.so
#15 0xed2667d5 in CServerGameDLL::GameFrame(bool) ()
   from /home/nxserv/gserv/servers/drp2/garrysmod/bin/server_srv.so
#16 0xf610d99d in SV_Think(bool) () from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#17 0xf610e335 in SV_Frame(bool) () from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#18 0xf60851d7 in _Host_RunFrame_Server(bool) () from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#19 0xf6086309 in _Host_RunFrame(float) () from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#20 0xf6086928 in Host_RunFrame(float) () from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#21 0xf608fc8e in CHostState::State_Run(float) () from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#22 0xf60900e6 in CHostState::FrameUpdate(float) () from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#23 0xf60901a9 in HostState_Frame(float) () from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#24 0xf612440c in CEngine::Frame() () from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#25 0xf6121a1d in CDedicatedServerAPI::RunFrame() () from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#26 0xf6c89d95 in RunServer() () from bin/dedicated_srv.so
#27 0xf6121e95 in CModAppSystemGroup::Main() () from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#28 0xf615e200 in CAppSystemGroup::Run() () from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#29 0xf6122457 in CDedicatedServerAPI::ModInit(ModInfo_t&) ()
   from /home/nxserv/gserv/servers/drp2/bin/engine_srv.so
#30 0xf6c89d02 in CDedicatedAppSystemGroup::Main() () from bin/dedicated_srv.so
#31 0xf6cd20b0 in CAppSystemGroup::Run() () from bin/dedicated_srv.so
#32 0xf6cd20b0 in CAppSystemGroup::Run() () from bin/dedicated_srv.so
#33 0xf6c8a182 in main () from bin/dedicated_srv.so
#34 0x08048872 in main ()
```

**Comment by Noiwex** [comment]
This timer is usually WireOverlayUpdate.

**Comment by Noiwex** [comment]
As far as I can tell, timers are unrelated to this; lua is not to blame.

**Comment by meepdarknessmeep** [comment]
Maybe if you uploaded the fucking mdmp file we could help. This isn't going to get magically fixed without it. Stop being a dickwad, and thinking that it will contain any private info at all. It's a mdmp, not a government paper with all your information and bank accounts on it.

**Comment by Noiwex** [comment]
Stop being so offensive, this place isn't your school class.

I have full core dumps, not minidumps. And they indeed contain some parts,
which are not meant to be shared with anyone.

**Comment by meepdarknessmeep** [comment]
Seriously are you fucking brain damaged
Core files are minidumps, they contain DEBUGGING information, not your rcon
password, not your 1337 shitcode, and not the password to facepunch. Please
go fucking learn how to research what a core file is before you go rating
every post I made on fp in the last six weeks dumb again
I call you a fucking retard because you are one, you try to debug things
without any knowledge of assembly or probably c at all without the proper
debugging tools needed nor the knowledge to debug it. Not pasting the dump
file is only hurting you.

**Comment by thegrb93** [comment]
Someone ban this hothead

**Comment by Noiwex** [comment]
oh hey they're so mini

```
779M    15-12-15_17-41-03.core
806M    15-12-15_17-46-12.core
1.2G    15-12-15_19-16-58.core
749M    15-12-15_21-41-51.core
777M    15-12-15_22-41-37.core
726M    15-12-16_00-00-08.core
900M    15-12-16_08-37-55.core
753M    15-12-16_09-03-02.core
1.2G    15-12-16_16-33-07.core
1.1G    15-12-16_17-28-57.core
1.1G    15-12-16_18-32-10.core
1.2G    15-12-16_21-06-37.core
1.2G    15-12-16_21-32-28.core
1.1G    15-12-16_22-14-55.core
1009M   15-12-16_22-43-26.core
973M    15-12-17_10-24-41.core
822M    15-12-17_10-45-21.core
810M    15-12-17_11-09-13.core
778M    15-12-17_11-44-12.core
```

**Comment by VigiFyre** [comment]
These files are complete snapshots of process memory in moment of crash. They do contain passwords, luas and so on.
Meep, you are either actually trying to get access to private stuff or have no idea what you are talking about.
Either way, gtfo.

**Comment by meepdarknessmeep** [comment]
Will you all shut the fuck up? I meant to say Garry's Mod creates MINIDUMPS. Not just core files. Send the MINIDUMPS that it creates, like every other source engine game. Core files are indeed containing information that is private. Saying "omg please ban this guy" or "get the fuck out retard!!" to me isn't going to help you. I am trying to help Noi fix his problem, but he is too stubborn to do anything to help himself.

**Comment by Bo98** [comment]
Does Linux SRCDS even create a mdmp file?

**Comment by Noiwex** [comment]
I'm afraid not, I had to write my own thing to dump these huge corefiles and I haven't found a way to make minidumps yet.

**Comment by meepdarknessmeep** [comment]
Apparently according to @mcd1992 only Garry's Mod Clients dump mdmp files on linux. 

I apologize for being a asshat earlier.. but this still won't solve the problem I was saying earlier.

We either need a core file or a way to convert the core file to a mdmp file.

**Comment by Noiwex** [comment]
Funny that this crash can be prevented by not detecting what hitbox is
under traceline. But devs are more concerned about lightsabers from
workshop rather than fixing actual crashes.

And no, I will not just post coredump for everyone.
