### ISSUE TITLE
SIGSEGV on Linux when joining a particular server

### ISSUE THREAD

**Issue by CyberShadow** [Facepunch/garrysmod-issues#2995]
Hello,

I'm seeing a SIGSEGV on all of three different systems (all running GNU/Linux) when trying to connect to a particular server.

The IP of the server in question is: `195.62.53.240:27015`

We haven't observed such crashes when joining other servers; only that one.

The systems in question are:
* A Dell laptop with a GeForce GTX 650M GPU running Ubuntu 16.10 amd64
* A Sony SVS15123CXB laptop with an i5-3210M CPU and its integrated Intel graphics, running Kubuntu 16.04 amd64
* A desktop with a i7-4960X CPU and a GeForce GTX TITAN GPU, running Arch Linux amd64.

Here is a gdb stack trace from the desktop machine:

```
Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
0xefeee24e in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
(gdb) where
#0  0xefeee24e in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#1  0xefeb8e84 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#2  0xefebcca0 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#3  0xefebd282 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#4  0xefebd468 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#5  0xefebd4d2 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#6  0xefed0297 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#7  0xefed18ba in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#8  0xefe7f1da in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#9  0xefeca05f in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#10 0xeb87b8ad in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/stdshader_dx9.so
#11 0xeb83c546 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/stdshader_dx9.so
#12 0xeb84acf9 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/stdshader_dx9.so
#13 0xeb87b331 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/stdshader_dx9.so
#14 0xefec986d in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#15 0xefe731ae in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#16 0xefe73265 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/materialsystem.so
#17 0xed9f6136 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/studiorender.so
#18 0xed9f6450 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/studiorender.so
#19 0xed9f9204 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/studiorender.so
#20 0xeddf539a in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/datacache.so
#21 0xeddfa084 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/datacache.so
#22 0xeddf906f in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/datacache.so
#23 0xeddfb2d2 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/datacache.so
#24 0xeddfb6f2 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/datacache.so
#25 0xf089f9fd in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#26 0xf08a0dcd in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#27 0xf08a388d in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#28 0xf08a4a6c in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#29 0xf0761c51 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#30 0xf078e7ee in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#31 0xf07634d5 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#32 0xf076362f in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#33 0xf08524b7 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#34 0xf0852926 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#35 0xf08536b8 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#36 0xf0868741 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#37 0xf086898e in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#38 0xf0868a99 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#39 0xf0943d32 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#40 0xf0940ccf in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#41 0xf0940ddd in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#42 0xf09c2790 in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#43 0xf0941ddf in ?? () from /home/steam/.local/share/Steam/steamapps/common/GarrysMod/bin/engine.so
#44 0xf5cf9250 in ?? ()
#45 0xf5cf9250 in ?? ()
#46 0xf5cdce6f in ?? ()
#47 0x080486db in main ()
```

And here is a stack trace from the Sony laptop (note that it's significantly different from the one above):

```
Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
0xf220bb16 in ?? ()
   from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
(gdb) where
#0  0xf220bb16 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#1  0xf220bbb0 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#2  0xf220cc38 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#3  0xf5dacaae in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/libtier0.so
#4  0xf5dacecc in Error () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/libtier0.so
#5  0xeec50740 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/shaderapidx9.so
#6  0xeec52812 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/shaderapidx9.so
#7  0xef29b34b in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/studiorender.so
#8  0xef29bcc2 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/studiorender.so
#9  0xef29bf95 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/studiorender.so
#10 0xef29c229 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/studiorender.so
#11 0xef69839a in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/datacache.so
#12 0xef69d084 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/datacache.so
#13 0xef69c06f in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/datacache.so
#14 0xef69e2d2 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/datacache.so
#15 0xef69e6f2 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/datacache.so
#16 0xf216c9fd in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#17 0xf216ddcd in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#18 0xf217088d in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#19 0xf2171a6c in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#20 0xf202ec51 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#21 0xf205b7ee in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#22 0xf20304d5 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#23 0xf203062f in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#24 0xf211f4b7 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#25 0xf211f926 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#26 0xf21206b8 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#27 0xf2135741 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#28 0xf213598e in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#29 0xf2135a99 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#30 0xf2210d32 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#31 0xf220dccf in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#32 0xf220dddd in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#33 0xf228f790 in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#34 0xf220eddf in ?? () from /home/vladimir-ne/.local/share/Steam/SteamApps/common/GarrysMod/bin/engine.so
#35 0xf5df4250 in ?? ()
#36 0xf5df4250 in ?? ()
#37 0xf5dd7e6f in ?? ()
#38 0x080486db in main ()
```

The stack traces are for Garry's Mod version `2016.12.20`.

The crashes seem to vary depending on the circumstances, such as machine and graphics driver. For example, on the Dell laptop, the crash occurs with both NVIDIA proprietary drivers and the Nouveau drivers, however in the latter case (as well as on the Sony laptop), the crash is preceded by an error message popup about vertex buffers (e.g. `failed to lock vertex buffer in CMeshXD8::LockVertexBuffer`). The exact error message varies between runs.

**Comment by robotboy655** [comment]
Closing as stale.
