### ISSUE TITLE
Linux Server Crash

### ISSUE THREAD

**Issue by blobles-dev** [Facepunch/garrysmod-issues#4875]
Linux server crashed not long after changelevel,

debug.log
```
[New LWP 21]
[New LWP 44]
[New LWP 53]
[New LWP 23]
[New LWP 56]
[New LWP 892]
[New LWP 54]
[New LWP 41]
[New LWP 28]
[New LWP 26]
[New LWP 24]
[New LWP 51]
[New LWP 52]
[New LWP 893]
[New LWP 22]
[New LWP 45]
[New LWP 47]
[New LWP 25]
[New LWP 27]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./srcds_linux -game garrysmod -console -port 27015 +ip 51.81.116.29 -strictport'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf2ef56f3 in CMDLCache::GetVCollideEx(unsigned short, bool) () from /home/container/bin/datacache_srv.so
[Current thread is 1 (Thread 0xf7255fc0 (LWP 21))]
#0  0xf2ef56f3 in CMDLCache::GetVCollideEx(unsigned short, bool) () from /home/container/bin/datacache_srv.so
#1  0xf2ef5b81 in CMDLCache::GetVCollide(unsigned short) () from /home/container/bin/datacache_srv.so
#2  0xf5bf0d8a in CModelInfo::GetVCollide(int) () from /home/container/bin/engine_srv.so
#3  0xf21c3be7 in CBaseAnimating::SetModel(char const*) () from /home/container/garrysmod/bin/server_srv.so
#4  0xf2043c00 in Entity__SetModel(ILuaInterface*) () from /home/container/garrysmod/bin/server_srv.so
#5  0xeea38c19 in lj_BC_FUNCC () from /home/container/garrysmod/bin/lua_shared_srv.so
#6  0xeea2c0f8 in lua_pcall () from /home/container/garrysmod/bin/lua_shared_srv.so
#7  0xee9f65bc in CLuaInterface::PCall(int, int, int) () from /home/container/garrysmod/bin/lua_shared_srv.so
#8  0xee9ff9e6 in CLuaInterface::CallFunctionProtected(int, int, bool) () from /home/container/garrysmod/bin/lua_shared_srv.so
#9  0xee9f768c in CLuaInterface::CallInternalNoReturns(int) () from /home/container/garrysmod/bin/lua_shared_srv.so
#10 0xf200f65f in LuaConCommand(CCommand const&) () from /home/container/garrysmod/bin/server_srv.so
#11 0xf5c449ac in CGameClient::ExecuteStringCommand(char const*) () from /home/container/bin/engine_srv.so
#12 0xf5b6b60b in CBaseClient::ProcessStringCmd(NET_StringCmd*) () from /home/container/bin/engine_srv.so
#13 0xf5b2ccf8 in NET_StringCmd::Process() () from /home/container/bin/engine_srv.so
#14 0xf5c0e252 in CNetChan::ProcessMessages(bf_read&) () from /home/container/bin/engine_srv.so
#15 0xf5c0e5a3 in CNetChan::CheckReceivingList(int) () from /home/container/bin/engine_srv.so
#16 0xf5c0e88f in CNetChan::ProcessPacket(netpacket_s*, bool) () from /home/container/bin/engine_srv.so
#17 0xf5c16b0e in NET_ProcessSocket(int, IConnectionlessPacketHandler*) () from /home/container/bin/engine_srv.so
#18 0xf5b7a78e in CBaseServer::RunFrame() () from /home/container/bin/engine_srv.so
#19 0xf5c56b7e in SV_Frame(bool) () from /home/container/bin/engine_srv.so
#20 0xf5bd4f5e in _Host_RunFrame_Server(bool) () from /home/container/bin/engine_srv.so
#21 0xf5bd58b4 in _Host_RunFrame(float) () from /home/container/bin/engine_srv.so
#22 0xf5be1ab8 in CHostState::State_Run(float) () from /home/container/bin/engine_srv.so
#23 0xf5be1d96 in CHostState::FrameUpdate(float) () from /home/container/bin/engine_srv.so
#24 0xf5be1ddd in HostState_Frame(float) () from /home/container/bin/engine_srv.so
#25 0xf5c6bd58 in CEngine::Frame() () from /home/container/bin/engine_srv.so
#26 0xf5c69906 in CDedicatedServerAPI::RunFrame() () from /home/container/bin/engine_srv.so
#27 0xf705e09a in RunServer() () from bin/dedicated_srv.so
#28 0xf5c699ad in CModAppSystemGroup::Main() () from /home/container/bin/engine_srv.so
#29 0xf5cbf628 in CAppSystemGroup::Run() () from /home/container/bin/engine_srv.so
#30 0xf5c69cbd in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /home/container/bin/engine_srv.so
#31 0xf705dd58 in CDedicatedAppSystemGroup::Main() () from bin/dedicated_srv.so
#32 0xf70ba8e8 in CAppSystemGroup::Run() () from bin/dedicated_srv.so
#33 0xf70ba8e8 in CAppSystemGroup::Run() () from bin/dedicated_srv.so
#34 0xf700b4fa in main () from bin/dedicated_srv.so
#35 0x08048aab in main ()
No symbol table info available.
eax            0x202844a0	539509920
ecx            0x4a	74
edx            0x1	1
ebx            0x0	0
esp            0xfffa2110	0xfffa2110
ebp            0xfffa2138	0xfffa2138
esi            0xf2f36c60	-218928032
edi            0xf2f36c60	-218928032
eip            0xf2ef56f3	0xf2ef56f3 <CMDLCache::GetVCollideEx(unsigned short, bool)+51>
eflags         0x10206	[ PF IF RF ]
cs             0x23	35
ss             0x2b	43
ds             0x2b	43
es             0x2b	43
fs             0x0	0
gs             0x63	99
From        To          Syms Read   Shared Object Library
0xf77179a0  0xf772d9f8  Yes (*)     bin/libtcmalloc_minimal.so.4
0xf76f8ad0  0xf76f9a84  Yes (*)     /lib/i386-linux-gnu/libdl.so.2
0xf76dd9d0  0xf76ed20f  Yes (*)     /lib/i386-linux-gnu/libpthread.so.0
0xf7515610  0xf7662386  Yes (*)     /lib/i386-linux-gnu/libc.so.6
0xf73e53a0  0xf74a29c4  Yes (*)     /usr/lib/i386-linux-gnu/libstdc++.so.6
0xf727e590  0xf733e8f5  Yes (*)     /lib/i386-linux-gnu/libm.so.6
0xf72590b0  0xf726eb55  Yes (*)     /lib/i386-linux-gnu/libgcc_s.so.1
0xf775aab0  0xf77757fb  Yes (*)     /lib/ld-linux.so.2
0xf72319b0  0xf7245c38  Yes (*)     bin/libtier0_srv.so
0xf721f910  0xf72233a4  Yes (*)     /lib/i386-linux-gnu/librt.so.1
0xf7136d60  0xf71595f8  Yes (*)     bin/libvstdlib_srv.so
0xf700a380  0xf70dbc44  Yes (*)     bin/dedicated_srv.so
0xf6f87780  0xf6fb3fb4  Yes (*)     bin/libsteam_api.so
0xf6653e80  0xf665fe44  Yes (*)     /lib/i386-linux-gnu/libtinfo.so.5
0xf5b0fb40  0xf5cdf464  Yes (*)     /home/container/bin/engine_srv.so
0xf5a6d5f0  0xf5a8ec13  Yes (*)     /home/container/bin/soundemittersystem_srv.so
0xf393ee10  0xf3a006b3  Yes (*)     /home/container/bin/materialsystem_srv.so
0xf30fdc50  0xf31a7313  Yes (*)     /home/container/bin/studiorender_srv.so
0xf2f65b60  0xf307ee30  Yes (*)     /home/container/bin/vphysics_srv.so
0xf2ecd3b0  0xf2f169e3  Yes (*)     /home/container/bin/datacache_srv.so
0xf2e9b400  0xf2eab973  Yes (*)     /home/container/bin/shaderapiempty_srv.so
0xf1ddae60  0xf28d6c34  Yes (*)     /home/container/garrysmod/bin/server_srv.so
0xf1938b90  0xf194a283  Yes (*)     /home/container/bin/scenefilecache_srv.so
0xeeababb0  0xeeac1554  Yes (*)     /lib/i386-linux-gnu/libnss_files.so.2
0xeeab2b70  0xeeab5ad4  Yes (*)     /lib/i386-linux-gnu/libnss_dns.so.2
0xeea9c660  0xeeaa84c4  Yes (*)     /lib/i386-linux-gnu/libresolv.so.2
0xee9f2a10  0xeea63214  Yes (*)     /home/container/garrysmod/bin/lua_shared_srv.so
0xec2bad80  0xed645104  Yes (*)     bin/steamclient.so
0xefaa7130  0xefacf064  Yes (*)     bin/crashhandler.so
0xeb0e8650  0xeb18982c  Yes (*)     bin/libSDL2-2.0.so.0
0xf0de50e0  0xf0f46e74  Yes         /home/container/garrysmod/lua/bin/gmsv_mysqloo_linux.dll
0xefb7d000  0xefdab644  Yes (*)     /home/container/garrysmod/lua/bin/gmsv_chttp_linux.dll
(*): Shared library is missing debugging information.
Dump of assembler code for function _ZN9CMDLCache13GetVCollideExEtb:
   0xf2ef56c0 <+0>:	push   %ebp
   0xf2ef56c1 <+1>:	mov    %esp,%ebp
   0xf2ef56c3 <+3>:	push   %edi
   0xf2ef56c4 <+4>:	push   %esi
   0xf2ef56c5 <+5>:	push   %ebx
   0xf2ef56c6 <+6>:	sub    $0x1c,%esp
   0xf2ef56c9 <+9>:	mov    0xf2f3701c,%ecx
   0xf2ef56cf <+15>:	mov    0x8(%ebp),%edi
   0xf2ef56d2 <+18>:	mov    0xc(%ebp),%eax
   0xf2ef56d5 <+21>:	mov    0x10(%ebp),%edx
   0xf2ef56d8 <+24>:	mov    0x30(%ecx),%ecx
   0xf2ef56db <+27>:	test   %ecx,%ecx
   0xf2ef56dd <+29>:	jne    0xf2ef5728 <_ZN9CMDLCache13GetVCollideExEtb+104>
   0xf2ef56df <+31>:	cmp    $0xffff,%ax
   0xf2ef56e3 <+35>:	je     0xf2ef5728 <_ZN9CMDLCache13GetVCollideExEtb+104>
   0xf2ef56e5 <+37>:	movzwl %ax,%ecx
   0xf2ef56e8 <+40>:	mov    %ecx,%eax
   0xf2ef56ea <+42>:	shl    $0x4,%eax
   0xf2ef56ed <+45>:	add    0x28(%edi),%eax
   0xf2ef56f0 <+48>:	mov    0xc(%eax),%ebx
=> 0xf2ef56f3 <+51>:	testb  $0x2,0x20(%ebx)
   0xf2ef56f7 <+55>:	je     0xf2ef5710 <_ZN9CMDLCache13GetVCollideExEtb+80>
   0xf2ef56f9 <+57>:	testw  $0x7fff,0x4(%ebx)
   0xf2ef56ff <+63>:	je     0xf2ef5728 <_ZN9CMDLCache13GetVCollideExEtb+104>
   0xf2ef5701 <+65>:	lea    0x4(%ebx),%eax
   0xf2ef5704 <+68>:	add    $0x1c,%esp
   0xf2ef5707 <+71>:	pop    %ebx
   0xf2ef5708 <+72>:	pop    %esi
   0xf2ef5709 <+73>:	pop    %edi
   0xf2ef570a <+74>:	pop    %ebp
   0xf2ef570b <+75>:	ret    
   0xf2ef570c <+76>:	lea    0x0(%esi,%eiz,1),%esi
   0xf2ef5710 <+80>:	movzbl %dl,%esi
   0xf2ef5713 <+83>:	mov    %ecx,0x4(%esp)
   0xf2ef5717 <+87>:	mov    %esi,0x8(%esp)
   0xf2ef571b <+91>:	mov    %edi,(%esp)
   0xf2ef571e <+94>:	call   0xf2ef4f30 <_ZN9CMDLCache19UnserializeVCollideEtb>
   0xf2ef5723 <+99>:	jmp    0xf2ef56f9 <_ZN9CMDLCache13GetVCollideExEtb+57>
   0xf2ef5725 <+101>:	lea    0x0(%esi),%esi
   0xf2ef5728 <+104>:	add    $0x1c,%esp
   0xf2ef572b <+107>:	xor    %eax,%eax
   0xf2ef572d <+109>:	pop    %ebx
   0xf2ef572e <+110>:	pop    %esi
   0xf2ef572f <+111>:	pop    %edi
   0xf2ef5730 <+112>:	pop    %ebp
   0xf2ef5731 <+113>:	ret    
End of assembler dump.
Stack level 0, frame at 0xfffa2140:
 eip = 0xf2ef56f3 in CMDLCache::GetVCollideEx(unsigned short, bool); saved eip = 0xf2ef5b81
 called by frame at 0xfffa2160
 Arglist at 0xfffa2138, args: 
 Locals at 0xfffa2138, Previous frame's sp is 0xfffa2140
 Saved registers:
  ebx at 0xfffa212c, ebp at 0xfffa2138, esi at 0xfffa2130, edi at 0xfffa2134, eip at 0xfffa213c
End of Source crash report
```

Console just before crash:
```
-------------------------------------------------------------------------------
CMDLCache::GetStudioHdr(0x4A) : invalid handle, not in dictionary (of size 298).
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
CMDLCache::GetStudioHdr(0x4A) : invalid handle, not in dictionary (of size 298).
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
CMDLCache::GetStudioHdr(0x4A) : invalid handle, not in dictionary (of size 298).
-------------------------------------------------------------------------------
Segmentation fault (core dumped)
```

**Comment by robotboy655** [comment]
20/03 is outdated by almost a year compared to the even live version of the game, not to mention changes in the dev beta.

**Comment by blobles-dev** [comment]
Sorry; should have been more clear, 20th March 2021 (today)

**Comment by robotboy655** [comment]
If it happens after todays update let me know. There are changes regarding models unloading on changelevel in todays update.

Closing until then.
