### ISSUE TITLE
2021.04.26 x86-64 Linux client crash

### ISSUE THREAD

**Issue by tatokis** [Facepunch/garrysmod-issues#4933]
### Details
Running the game from the `x86-64` branch (2021.04.26) on fully updated Ubuntu 20.04 results in a crash before it gets to the main menu.

Unfortunately I can't pinpoint the exact version in the `x86_64` branch that it stopped working, however the `chromium` branch works as expected, and is at version 2021.04.02, so it's probably something in-between those two releases.
The `stable` branch, which is also at 2021.04.02, works as well.

gdb backtrace:
```
Thread 1 "gmod" received signal SIGSEGV, Segmentation fault.
0x00007f7a7bbac263 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007f7a7bbac263 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) () at /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007f7a77e58d88 in  () at steamapps/common/GarrysMod/bin/linux64/filesystem_stdio_client.so
#2  0x00007f7a77e59021 in  () at steamapps/common/GarrysMod/bin/linux64/filesystem_stdio_client.so
#3  0x00007f7a77e64586 in  () at steamapps/common/GarrysMod/bin/linux64/filesystem_stdio_client.so
#4  0x00007f7a77e56fb7 in  () at steamapps/common/GarrysMod/bin/linux64/filesystem_stdio_client.so
#5  0x00007f7975da6ed8 in  () at steamapps/common/GarrysMod/bin/linux64/server_client.so
#6  0x00007f79af075db6 in  () at steamapps/common/GarrysMod/bin/linux64/engine_client.so
#7  0x00007f79af0fb164 in  () at steamapps/common/GarrysMod/bin/linux64/engine_client.so
#8  0x00007f79af0feed8 in  () at steamapps/common/GarrysMod/bin/linux64/engine_client.so
#9  0x00007f79af108c51 in  () at steamapps/common/GarrysMod/bin/linux64/engine_client.so
#10 0x00007f79af108fbe in  () at steamapps/common/GarrysMod/bin/linux64/engine_client.so
#11 0x00007f79af174c26 in  () at steamapps/common/GarrysMod/bin/linux64/engine_client.so
#12 0x00007f79af172335 in  () at steamapps/common/GarrysMod/bin/linux64/engine_client.so
#13 0x00007f79af17245a in  () at steamapps/common/GarrysMod/bin/linux64/engine_client.so
#14 0x00007f79af2ce4b9 in  () at steamapps/common/GarrysMod/bin/linux64/engine_client.so
#15 0x00007f79af17312c in  () at steamapps/common/GarrysMod/bin/linux64/engine_client.so
#16 0x00007f7a79f5bbf9 in  () at steamapps/common/GarrysMod/bin/linux64/launcher_client.so
#17 0x00007f7a79f5bbf9 in  () at steamapps/common/GarrysMod/bin/linux64/launcher_client.so
#18 0x00007f7a79f38634 in  () at steamapps/common/GarrysMod/bin/linux64/launcher_client.so
#19 0x00007f7a79ce71ce in Dump_CallMainFunction () at steamapps/common/GarrysMod/bin/linux64/libtier0_client.so
#20 0x0000000000400a56 in main ()
```

Since the segfault seems to be caused by `filesystem_stdio_client.so` I thought I'd attach strace to see if a specific addon file caused the crash, however the crash occurs after the game finishes processing the addons and starts loading the game modes.
The last few file accesses according to strace are:
```
[pid 444405] openat(AT_FDCWD, "[path]/steamapps/common/Team Fortress 2/tf", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 425
[pid 444405] openat(AT_FDCWD, "/media/tatokis/Data/STeamLinuxApp/Steam/steamapps/common/Counter-Strike Source/cstrike", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 425
[pid 444405] openat(AT_FDCWD, "[path]/steamapps/common/GarrysMod/garrysmod/download", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 425
[pid 444405] openat(AT_FDCWD, "[path]/steamapps/common/GarrysMod/garrysmod", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 425
[pid 444405] openat(AT_FDCWD, "/proc/444404/cmdline", O_RDONLY) = 425
[pid 444405] openat(AT_FDCWD, "/proc/444404/cmdline", O_RDONLY) = 425
[pid 444405] openat(AT_FDCWD, "/proc/444404/cmdline", O_RDONLY) = 425
[pid 444405] openat(AT_FDCWD, "/proc/444404/cmdline", O_RDONLY) = 425
[pid 444405] openat(AT_FDCWD, "[path]/steamapps/common/GarrysMod/garrysmod/overrides/gamemodes/sandbox", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (Δεν υπάρχει τέτοιο αρχείο ή κατάλογος)
[pid 444405] openat(AT_FDCWD, "[path]/steamapps/common/GarrysMod/garrysmod/gamemodes/sandbox", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 425
[pid 444405] openat(AT_FDCWD, "/proc/444404/cmdline", O_RDONLY) = 425
[pid 444405] openat(AT_FDCWD, "/proc/444404/cmdline", O_RDONLY) = 425
[pid 444405] openat(AT_FDCWD, "/proc/444404/cmdline", O_RDONLY) = 425
[pid 444405] openat(AT_FDCWD, "/proc/444404/cmdline", O_RDONLY) = 425
[pid 444405] openat(AT_FDCWD, "[path]/steamapps/common/GarrysMod/garrysmod/overrides/gamemodes/base", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (Δεν υπάρχει τέτοιο αρχείο ή κατάλογος)
[pid 444405] openat(AT_FDCWD, "[path]/steamapps/common/GarrysMod/garrysmod/gamemodes/base", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 425
[pid 444405] openat(AT_FDCWD, "/proc/444404/cmdline", O_RDONLY) = 425
[pid 444405] --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
[pid 444405] --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
[pid 444405] --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
[pid 444405] --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
```

### Steps to reproduce
Run the x86-64 beta client.
Observe the segfault during the "Mounting workshop items" phase.

**Comment by robotboy655** [comment]
This should be fixed.
