### ISSUE TITLE
There is No Main Menu

### ISSUE THREAD

**Issue by GordonFHL3** [Facepunch/garrysmod-issues#689]
![hl2 2014-01-03 13-09-56-95](https://f.cloud.github.com/assets/6312757/1840943/129d1d7a-749b-11e3-9451-67cbc89ccfbb.jpg)
GMod Version: 13.12.06
OS: Windows 7 Ultimate 64 Bits
Error: No menu when GMod I start GMod
There always 35 files that Steam can't verify

[HTML] SyntaxError: Unexpected identifier
    at eval (native)
    at asset://garrysmod/html/js/thirdparty/jquery.js:2:11530
    at Function.globalEval (asset://garrysmod/html/js/thirdparty/jquery.js:2:11540)
    at HTMLScriptElement.bp (asset://garrysmod/html/js/thirdparty/jquery.js:2:3293)
    at Function.each (asset://garrysmod/html/js/thirdparty/jquery.js:2:11937)
    at [object Object].domManip (asset://garrysmod/html/js/thirdparty/jquery.js:4:1920)
    at [object Object].append (asset://garrysmod/html/js/thirdparty/jquery.js:3:31818)
    at [object Object].<anonymous> (asset://garrysmod/html/js/thirdparty/jquery.js:4:776)
    at [object Object].c [as html] (asset://garrysmod/html/js/thirdparty/angular.js:18:419)
    at k (asset://garrysmod/html/js/thirdparty/angular.js:145:78)

**Comment by willox** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/2458

**Comment by willox** [comment]
Will be fixed on the dev branch within an hour or so.

**Comment by Rakosnakak** [comment]
Thx very much :)


---------- Původní zpráva ----------

Od: William Wallace <notifications@github.com>

Komu: Facepunch/garrysmod-issues <garrysmod-issues@noreply.github.com>

Datum: 14. 3. 2016 19:11:13

Předmět: Re: [garrysmod-issues] There is No Main Menu (#689)


"

Will be fixed on the dev branch within an hour or so.

—

Reply to this email directly or view it on GitHub
(https://github.com/Facepunch/garrysmod-issues/issues/689#issuecomment-196447590)
. 





"=

**Comment by Redotix99** [comment]
still not fixed lol

**Comment by robotboy655** [comment]
@Redotix99 Try -chromium on Dev branch and see if it fixes the problem.

**Comment by arthurdead** [comment]
i was having this problem then i noticed in the console
No support for unprivileged usernamespaces. Loading Stub instead of Chromium...

then i googled that and found the command
sudo sysctl -w kernel.unprivileged_userns_clone=1

and that actually fixed it so if anyone is having this problem the above command should fix it

**Comment by Rakosnakak** [comment]
If I've still had this problem, I would try. But I hope no one will ever come across it again, such a ugly bug!

**Comment by linkjay** [comment]
@arthurdead Can confirm that worked for me and solved my issue!

**Comment by GitAntoinee** [comment]
Hello, I had the same problem and I added `en_US.UTF-8 UTF-8` to `/etc/locale.gen` and I run `locale-gen` as root

**Comment by drincoxyz** [comment]
> i was having this problem then i noticed in the console
> No support for unprivileged usernamespaces. Loading Stub instead of Chromium...
> 
> then i googled that and found the command
> sudo sysctl -w kernel.unprivileged_userns_clone=1
> 
> and that actually fixed it so if anyone is having this problem the above command should fix it

To add onto this, you can also enable this feature directly in the kernel if you're on Gentoo (or if you just compile your kernel images in general) — the variable is [CONFIG_USER_NS](https://cateee.net/lkddb/web-lkddb/USER_NS.html).

I know this issue tracker applies to Windows, and looks like a different cause entirely, but it's also pretty easy to run into this exact problem (no menu) if you have a specific setup with Linux, so I figured it'd be worth mentioning.

**Comment by BorealBlizzard** [comment]
> @Redotix99 Try -chromium on Dev branch and see if it fixes the problem.
This fixed the problem for me on Manjaro

**Comment by rileysu** [comment]
If someone runs into this issue like me then none of these other solutions seemed to work apart from this one:
https://github.com/solsticegamestudios/GModCEFCodecFix

Widevine failed to load on mine as well as some other issues and that was preventing chromium from starting and displaying the UI.

**Comment by peppermp3** [comment]
Ive ran into the same issues, Ive tried the following:

restarted pc
cold restarted pc
verified files
deleted main menu files in lua/ and reinstalled
clean installed gmod
tried launching in 32 bit
tried GmodCEFCodecFix

Heres a screenshot of my console:
![image](https://user-images.githubusercontent.com/127553499/224432988-821e6805-90d1-487c-a9c9-fbd434c832d1.png)
